### ISSUE TITLE
Remove Scoreloop

### ISSUE THREAD

**Issue by amitie10g** [ellenhp/TuxRacer-SDL2#1]
First, good job to make this port.

As I noticied, the game still contains the Scoreloop code, that becomes very annoying, and is useless due the service is not longer available. Please try to remove that.

And regarding the scoring system, are you considerin to use another system like Google Play Games or anything else?

**Comment by lenniea** [comment]
Yes I'm planning on moving to another system - it was unfortunate that Scoreloop closed down.
I don't want to use Google Play because the game is written for the OUYA platform as well (which doesn't support Google Play Services).
-Lennie

Date: Fri, 23 Oct 2015 08:02:50 -0700

**Comment by amitie10g** [comment]
Then, is possible to remove for now them, meanwhile you find another scoring system? The Scoreloop messages are really annoying and I don't want that this project have negative votes in the Play Store due to that :(

**Comment by lenniea** [comment]
I will try but I am also moving my projects from Eclipse to Android Studio (which doesn't have very good support for NDK projects like Tux Racer).
-Lennie

Date: Fri, 23 Oct 2015 08:13:30 -0700

**Comment by ellenhp** [comment]
Believe this is resolved. Spare time permitting, I'm going to be overhauling some parts of the project and releasing an update after the holidays so stay tuned.
